---
- name: Create Datadog Agent Zookeeper Monitoring Config File
  template:
    src: zk.yaml.j2
    dest: /etc/datadog-agent/conf.d/zk.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644
