---
- name: Create Datadog Agent PostgreSQL Monitoring Config File
  template:
    src: postgres.yaml.j2
    dest: /etc/datadog-agent/conf.d/postgres.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644
