- hosts: agent
  any_errors_fatal: true
  roles:
    - role: agent

- hosts: tcp-check
  any_errors_fatal: true
  roles:
    - role: agent
    - role: tcp-check

- hosts: http-check
  any_errors_fatal: true
  roles:
    - role: agent
    - role: http-check

- hosts: kafka
  any_errors_fatal: true
  roles:
    - role: agent
    - role: kafka
    - role: systemd

- hosts: zookeeper
  any_errors_fatal: true
  roles:
    - role: agent
    - role: zookeeper
    - role: systemd

- hosts: elasticsearch
  any_errors_fatal: true
  roles:
    - role: agent
    - role: elasticsearch
    - role: systemd

- hosts: nginx
  any_errors_fatal: true
  roles:
    - role: agent
    - role: nginx
    - role: systemd
