- hosts: all
  any_errors_fatal: true
  roles:
    - role: agent

- hosts: tcp_check
  any_errors_fatal: true
  roles:
    - role: tcp_check

- hosts: http_check
  any_errors_fatal: true
  roles:
    - role: http_check

- hosts: mysql
  any_errors_fatal: true
  roles:
    - role: mysql
    - role: systemd

- hosts: postgresql
  any_errors_fatal: true
  roles:
    - role: postgresql
    - role: systemd

- hosts: mongodb
  any_errors_fatal: true
  roles:
    - role: mongodb
    - role: systemd

- hosts: kafka
  any_errors_fatal: true
  roles:
    - role: kafka
    - role: systemd

- hosts: zookeeper
  any_errors_fatal: true
  roles:
    - role: zookeeper
    - role: systemd

- hosts: elasticsearch
  any_errors_fatal: true
  roles:
    - role: elasticsearch
    - role: systemd

- hosts: nginx
  any_errors_fatal: true
  roles:
    - role: nginx
    - role: systemd
