---
- name: Add Service '{{ systemd_service_name }}' to SystemD Monitoring Config File
  lineinfile:
    path: /etc/datadog-agent/conf.d/systemd.d/conf.yaml
    regexp: '^\s*- unit_names:'
    insertafter: '^(\s*- unit_names:)\s*$'
    line: '    - {{ systemd_service_name }}'
