---
- name: Add Service '{{ systemd_service_name }}' to SystemD Monitoring Config File
  blockinfile:
    path: /etc/datadog-agent/conf.d/systemd.d/conf.yaml
    marker: ""
    block: |
      - {{ systemd_service_name }}
    insertafter: '^(\s*- unit_names:\s*)$'
