---
- name: Create Datadog Agent MySQL / MariaDB Monitoring Config File
  template:
    src: mysql.yaml.j2
    dest: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644
