---
- name: Create Datadog Agent TCP Check Monitoring Config File
  template:
    src: tcp_check.yaml.j2
    dest: /etc/datadog-agent/conf.d/tcp_check.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644
