---
- name: Fail if TCP Check Name Variable is not set
  fail:
    msg: "TCP Check Name Variable is not set"
  when:
    - tcp_check_name is not defined or tcp_check_name == ''

- name: Fail if TCP Check Host Variable is not set
  fail:
    msg: "TCP Check Host Variable is not set"
  when:
    - tcp_check_host is not defined or tcp_check_host == ''

- name: Fail if TCP Check Port Variable is not set
  fail:
    msg: "TCP Check Port Variable is not set"
  when:
    - tcp_check_port is not defined or tcp_check_port == ''
