---
- name: Create Datadog Agent ElasticSearch Monitoring Config File
  template:
    src: elastic.yaml.j2
    dest: /etc/datadog-agent/conf.d/elastic.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644
